CREATE TABLE GENERO (
 NOME VARCHAR(30) NOT NULL,
 ICONE CHAR(100),
 COR VARCHAR(10)
);

ALTER TABLE GENERO ADD CONSTRAINT PK_GENERO PRIMARY KEY (NOME);


CREATE TABLE MUSICA (
 CODIGO INT NOT NULL,
 CANTOR VARCHAR(50),
 GENERO CHAR(50),
 DURACAO TIME(10),
 NOME VARCHAR(50),
 URL_IMAGEM VARCHAR(255),
 NOME_GENERO VARCHAR(30)
);

ALTER TABLE MUSICA ADD CONSTRAINT PK_MUSICA PRIMARY KEY (CODIGO);


ALTER TABLE MUSICA ADD CONSTRAINT FK_MUSICA_0 FOREIGN KEY (NOME_GENERO) REFERENCES GENERO (NOME);


