CREATE DATABASE IF NOT EXISTS MeowMusic;
USE MeowMusic;

CREATE TABLE IF NOT EXISTS GENERO (
 NOME VARCHAR(100) NOT NULL PRIMARY KEY,
 ICONE VARCHAR(100),
 COR VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS MUSICA (
 CODIGO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 CANTOR VARCHAR(50),
 NOME VARCHAR(50),
 DURACAO TIME,
 URL_IMAGEM VARCHAR(255),
 NOME_GENERO VARCHAR(100), 
 ATIVO bool DEFAULT 1,
 CONSTRAINT FK_MUSICA_GENERO 
    FOREIGN KEY (NOME_GENERO) 
    REFERENCES GENERO (NOME)
);

CREATE TABLE IF NOT EXISTS LOGIN (
usuario VARCHAR(100) NOT NULL PRIMARY KEY,
senha VARCHAR(100) NOT NULL
);
